### ISSUE TITLE
Create orchestration service

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#12]
Due to a bug need a http service to inform replay-nodes of run options, and gather status information from nodes. 

```[tasklist]
### Tasks
- [ ] Write Python HTTP web service
- [ ] Get Call job, no args, returns get json below
- [ ] Put Call status, url has Job Number, pushed json 
```

Get Call 
```
{
job_number: num,
snapshot_loc: string,
blocklog_loc: string,
last_block: number
}
```

Put Call
`{ status:[ongoing|stopped|error|finished], block_number: last_block_num_processed }`
