### ISSUE TITLE
Create two AWS hosts for replay

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#3]
Transferred from https://github.com/AntelopeIO/leap/issues/1423 original author bhazzard

All installation of software from deb packages. Installation of config from this repo

```[tasklist]
### Tasks
- [x] AWS template for hosts
- [x] Init Shell script to create linux user, setup dirs, install nodeos
- [x] Create default config file
- [x] Create startup script for nodeos
- [x] Create shutdown script for nodeos
- [ ] make genesis file avalible
```
