### ISSUE TITLE
[REPLAY-20] Manual Update Blocklogs on S3

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#54]
```[tasklist]
### Tasks
- [ ] spin up an empty replay host, disable cron
- [ ] get list of blocks logs push to file 
- [ ] iterate through list create new blockslog with 2 million stride
- [ ] test and validate new blockslog
- [ ] compress and upload
```

Then automate a batch of 5 , then automate larger run.
