### ISSUE TITLE
Track Statistics in WebService

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#72]
```[tasklist]
### Tasks
- [ ] Create a statistics class to store stats
- [ ] Create new API POST/GET `/metrics` 
- [ ] Update stats on job complete
```
