### ISSUE TITLE
API to manage replay host instances on AWS

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#76]
Need HTTP API to start or terminate AWS replay hosts. Data should be held by webservice. 
 

```[tasklist]
### Tasks
- [ ] Create new class for hosts
- [ ] Create GET/POST API `/replayhost`
- [ ] UI to manage hosts 
```
