### ISSUE TITLE
Single Node Full Replay To Build Snapshots and Blockslogs

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#84]
Rerun from genesis building blocks logs and snapshots along the way. 

```[tasklist]
### Tasks
- [ ] Create new hosts with 9Tb of ESB storage
- [ ] create manifest file with block ranges that should take 3 hours or less
- [ ] research how to stride blockslogs every 2 million blocks. 
- [ ] Create script to start/stop/snapshot nodoes at specific block heights based on manifest 
- [ ] Script should also compress, backup blocks and snapshots 
```
