### ISSUE TITLE
Replay Hosts need big tmp space for blocks logs merge

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/replay-test#94]
Block logs span 2,000,000 blocks, and sometimes a replay needs blocks from a outside what a single block log can provide. That requires pulling down multiple block logs and merging them together. The current replay hosts do not have enough `/tmp` space for the merge, and this feature is disabled. Since the blocks are not available they are synced from peers. Fixing this will speed up replays because these cases will read from local blocks log. 

Fixing this issue requires the following:

```[tasklist]
### Tasks
- [ ] Increase `/tmp` space on replay hosts by updating user-data script
- [ ] Update `manage_blocks_log.sh` to process multiple block logs 
- [ ] Test new `manage_blocks_log.sh` that merge works
```

The script change is easy. Uncomment line 56 and comment out line 57. 
https://github.com/eosnetworkfoundation/replay-test/blob/118c616fedf01b933ce6ef3ed97aa6d84ca1972d/replay-client/manage_blocks_log.sh#L56-L57
